import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { Landmark,Plus,Scale } from 'lucide-react'
import { PageHeader } from '../../components/ui/page-header';import{Card}from'../../components/ui/card';import{Button}from'../../components/ui/button';import{Input}from'../../components/ui/input';import{Select}from'../../components/ui/select';import{Dialog}from'../../components/ui/dialog';import{useToast}from'../../components/ui/toast'
import{addBankTransaction,createBankAccount,listBankAccounts,listBankTransactions,listReconciliations,reconcileBank}from'../../lib/billing';import{formatSAR}from'../../lib/finance'
const today=()=>new Date().toISOString().slice(0,10)
export default function BankingPage(){const qc=useQueryClient(),{toast}=useToast();const[accountOpen,setAccountOpen]=useState(false),[txOpen,setTxOpen]=useState(false),[recOpen,setRecOpen]=useState(false);const[name,setName]=useState(''),[bankName,setBankName]=useState(''),[iban,setIban]=useState(''),[opening,setOpening]=useState(0);const[accountId,setAccountId]=useState(''),[date,setDate]=useState(today()),[direction,setDirection]=useState<'credit'|'debit'>('credit'),[amount,setAmount]=useState(0),[description,setDescription]=useState(''),[reference,setReference]=useState(''),[statement,setStatement]=useState(0)
const{data:accounts=[]}=useQuery({queryKey:['bank-accounts'],queryFn:listBankAccounts});const{data:txs=[]}=useQuery({queryKey:['bank-transactions'],queryFn:()=>listBankTransactions()});const{data:recs=[]}=useQuery({queryKey:['bank-reconciliations'],queryFn:listReconciliations});const refresh=()=>{void qc.invalidateQueries({queryKey:['bank-accounts']});void qc.invalidateQueries({queryKey:['bank-transactions']});void qc.invalidateQueries({queryKey:['bank-reconciliations']})};const accMut=useMutation({mutationFn:()=>createBankAccount({name,bankName,iban,openingBalance:opening}),onSuccess:()=>{toast('تم إنشاء الحساب');setAccountOpen(false);refresh()},onError:(e:Error)=>toast(e.message,'error')});const txMut=useMutation({mutationFn:()=>addBankTransaction({accountId,date,direction,amount,description,reference}),onSuccess:()=>{toast('تمت إضافة الحركة');setTxOpen(false);refresh()},onError:(e:Error)=>toast(e.message,'error')});const recMut=useMutation({mutationFn:()=>reconcileBank({accountId,periodEnd:date,statementBalance:statement}),onSuccess:()=>{toast('تم احتساب التسوية');setRecOpen(false);refresh()},onError:(e:Error)=>toast(e.message,'error')})
return <div className="space-y-6 pb-12"><PageHeader title="البنوك والتسوية البنكية" description="الحسابات والحركات ومطابقة الرصيد الدفتري مع كشف البنك" actions={<div className="flex gap-2"><Button variant="outline" onClick={()=>setTxOpen(true)}>حركة بنكية</Button><Button variant="outline" onClick={()=>setRecOpen(true)}><Scale className="size-4"/>تسوية</Button><Button onClick={()=>setAccountOpen(true)} className="bg-navy text-white"><Plus className="size-4"/>حساب</Button></div>}/><div className="grid gap-4 md:grid-cols-3">{accounts.map(a=><Card key={a.id} className="p-5"><Landmark className="size-5 text-navy"/><h3 className="mt-3 font-bold">{a.name}</h3><p className="text-xs text-ink-muted">{a.bankName}<br/>{a.iban}</p><p className="mt-3 text-xl font-bold">{formatSAR(a.balance)}</p></Card>)}{accounts.length===0&&<Card className="p-8 text-center text-sm text-ink-muted">أضف أول حساب بنكي</Card>}</div><Card className="overflow-x-auto bg-white p-5"><h3 className="mb-4 font-bold">الحركات البنكية</h3><table className="w-full text-sm"><tbody>{txs.map(t=><tr key={t.id} className="border-b"><td className="p-3">{t.date}</td><td className="p-3">{t.description}</td><td className={`p-3 font-bold ${t.direction==='credit'?'text-success':'text-danger'}`}>{t.direction==='credit'?'+':'-'} {formatSAR(t.amount)}</td><td className="p-3">{t.reconciled?'مطابق':'غير مطابق'}</td></tr>)}</tbody></table></Card><Card className="bg-white p-5"><h3 className="mb-3 font-bold">سجل التسويات</h3>{recs.map(r=><div key={r.id} className="flex justify-between border-b py-3 text-sm"><span>{r.periodEnd}</span><span>الفرق: {formatSAR(r.difference)}</span><span>{r.status==='completed'?'مكتملة':'تحتاج مراجعة'}</span></div>)}</Card>
<Dialog open={accountOpen} onClose={()=>setAccountOpen(false)} title="حساب بنكي جديد"><form onSubmit={e=>{e.preventDefault();accMut.mutate()}} className="space-y-3"><Input placeholder="اسم الحساب" value={name} onChange={e=>setName(e.target.value)} required/><Input placeholder="اسم البنك" value={bankName} onChange={e=>setBankName(e.target.value)} required/><Input dir="ltr" placeholder="IBAN" value={iban} onChange={e=>setIban(e.target.value)}/><Input type="number" step="0.01" placeholder="الرصيد الافتتاحي" value={opening} onChange={e=>setOpening(Number(e.target.value))}/><Button className="w-full bg-navy text-white">حفظ</Button></form></Dialog>
<Dialog open={txOpen} onClose={()=>setTxOpen(false)} title="إضافة حركة بنكية"><form onSubmit={e=>{e.preventDefault();txMut.mutate()}} className="space-y-3"><Select value={accountId} onChange={e=>setAccountId(e.target.value)} options={[{value:'',label:'اختر الحساب'},...accounts.map(a=>({value:a.id,label:a.name}))]}/><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/><Select value={direction} onChange={e=>setDirection(e.target.value as any)} options={[{value:'credit',label:'إيداع / دائن'},{value:'debit',label:'سحب / مدين'}]}/><Input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><Input placeholder="الوصف" value={description} onChange={e=>setDescription(e.target.value)}/><Input placeholder="المرجع" value={reference} onChange={e=>setReference(e.target.value)}/><Button className="w-full bg-navy text-white">حفظ الحركة</Button></form></Dialog>
<Dialog open={recOpen} onClose={()=>setRecOpen(false)} title="تسوية بنكية"><form onSubmit={e=>{e.preventDefault();recMut.mutate()}} className="space-y-3"><Select value={accountId} onChange={e=>setAccountId(e.target.value)} options={[{value:'',label:'اختر الحساب'},...accounts.map(a=>({value:a.id,label:a.name}))]}/><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/><Input type="number" step="0.01" placeholder="الرصيد حسب كشف البنك" value={statement} onChange={e=>setStatement(Number(e.target.value))}/><Button className="w-full bg-navy text-white">احتساب ومطابقة</Button></form></Dialog></div>}
