import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { FileText, Loader2, Plus, Receipt, Wallet } from 'lucide-react'
import { PageHeader } from '../../components/ui/page-header'
import { Card } from '../../components/ui/card'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import { Select } from '../../components/ui/select'
import { Dialog } from '../../components/ui/dialog'
import { useToast } from '../../components/ui/toast'
import { createInvoice, listBankAccounts, listInvoiceClients, listInvoices, recordInvoicePayment, type Invoice, type InvoiceItemInput } from '../../lib/billing'
import { formatSAR, PAYMENT_METHOD_AR, type PaymentMethod } from '../../lib/finance'

const today=()=>new Date().toISOString().slice(0,10)
const initialItem=():InvoiceItemInput=>({description:'',quantity:1,unitPrice:0,vatRate:15})
export default function InvoicesPage(){
 const qc=useQueryClient(),{toast}=useToast(); const [open,setOpen]=useState(false),[paying,setPaying]=useState<Invoice|null>(null)
 const [clientId,setClientId]=useState(''),[issueDate,setIssueDate]=useState(today()),[dueDate,setDueDate]=useState(today()),[notes,setNotes]=useState(''),[items,setItems]=useState<InvoiceItemInput[]>([initialItem()])
 const [payAmount,setPayAmount]=useState(0),[payMethod,setPayMethod]=useState<PaymentMethod>('transfer'),[bankId,setBankId]=useState(''),[reference,setReference]=useState('')
 const {data:invoices=[]}=useQuery({queryKey:['invoices'],queryFn:listInvoices});const{data:clients=[]}=useQuery({queryKey:['invoice-clients'],queryFn:listInvoiceClients});const{data:banks=[]}=useQuery({queryKey:['bank-accounts'],queryFn:listBankAccounts})
 const total=useMemo(()=>items.reduce((n,i)=>n+i.quantity*i.unitPrice*(1+i.vatRate/100),0),[items])
 const refresh=()=>{void qc.invalidateQueries({queryKey:['invoices']});void qc.invalidateQueries({queryKey:['finance-records']});void qc.invalidateQueries({queryKey:['bank-accounts']})}
 const createMut=useMutation({mutationFn:()=>createInvoice({clientId,issueDate,dueDate,notes,items}),onSuccess:()=>{toast('تم إنشاء الفاتورة');setOpen(false);refresh()},onError:(e:Error)=>toast(e.message,'error')})
 const payMut=useMutation({mutationFn:()=>recordInvoicePayment({invoiceId:paying!.id,amount:payAmount,date:today(),method:payMethod,reference,bankAccountId:bankId||undefined}),onSuccess:()=>{toast('تم تسجيل السداد وربطه بالسجل المالي');setPaying(null);refresh()},onError:(e:Error)=>toast(e.message,'error')})
 const stats={total:invoices.reduce((n,i)=>n+i.total,0),due:invoices.reduce((n,i)=>n+i.total-i.paid,0),paid:invoices.reduce((n,i)=>n+i.paid,0)}
 return <div className="space-y-6 pb-12"><PageHeader title="الفواتير والتحصيل" description="إصدار الفواتير وتسجيل الدفعات وربطها بالسجل المالي" action={<Button id="tour-invoices-new" onClick={()=>setOpen(true)} className="gap-2 bg-navy text-white"><Plus className="size-4"/>فاتورة جديدة</Button>}/>
 <div id="tour-invoices-metrics" className="grid gap-4 md:grid-cols-3">{[['إجمالي الفواتير',stats.total],['المحصل',stats.paid],['المتبقي',stats.due]].map(([l,v])=><Card key={String(l)} className="p-5"><p className="text-xs text-ink-muted">{l}</p><p className="mt-2 text-2xl font-bold text-navy">{formatSAR(Number(v))}</p></Card>)}</div>
 <Card id="tour-invoices-table" className="overflow-x-auto bg-white p-5"><table className="w-full text-sm"><thead><tr className="border-b text-right text-xs text-ink-muted">{['الرقم','العميل','الإصدار','الاستحقاق','الإجمالي','المتبقي','الحالة',''].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{invoices.map(i=><tr key={i.id} className="border-b"><td className="p-3 font-mono">{i.number}</td><td className="p-3 font-bold">{i.clientName}</td><td className="p-3">{i.issueDate}</td><td className="p-3">{i.dueDate}</td><td className="p-3">{formatSAR(i.total)}</td><td className="p-3">{formatSAR(i.total-i.paid)}</td><td className="p-3">{i.status}</td><td className="p-3">{i.status!=='paid'&&i.status!=='void'&&<Button size="sm" onClick={()=>{setPaying(i);setPayAmount(i.total-i.paid)}}>تسجيل سداد</Button>}</td></tr>)}</tbody></table>{invoices.length===0&&<p className="py-10 text-center text-sm text-ink-muted">لا توجد فواتير بعد</p>}</Card>
 <Dialog open={open} onClose={()=>setOpen(false)} title="إنشاء فاتورة" wide><form onSubmit={e=>{e.preventDefault();if(!clientId||items.some(i=>!i.description||i.quantity<=0||i.unitPrice<0)){toast('أكمل بيانات الفاتورة','error');return}createMut.mutate()}} className="space-y-4"><Select value={clientId} onChange={e=>setClientId(e.target.value)} options={[{value:'',label:'اختر العميل'},...clients.map(c=>({value:c.id,label:`${c.full_name} — ${c.reference_number}`}))]}/><div className="grid gap-3 sm:grid-cols-2"><Input type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)}/><Input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></div>
 {items.map((it,idx)=><div key={idx} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-[2fr_.6fr_1fr_.7fr_auto]"><Input placeholder="وصف البند" value={it.description} onChange={e=>setItems(items.map((x,j)=>j===idx?{...x,description:e.target.value}:x))}/><Input type="number" min="0.01" step="0.01" value={it.quantity} onChange={e=>setItems(items.map((x,j)=>j===idx?{...x,quantity:Number(e.target.value)}:x))}/><Input type="number" min="0" step="0.01" value={it.unitPrice} onChange={e=>setItems(items.map((x,j)=>j===idx?{...x,unitPrice:Number(e.target.value)}:x))}/><Input type="number" min="0" max="100" value={it.vatRate} onChange={e=>setItems(items.map((x,j)=>j===idx?{...x,vatRate:Number(e.target.value)}:x))}/><button type="button" onClick={()=>items.length>1&&setItems(items.filter((_,j)=>j!==idx))}>×</button></div>)}<Button type="button" variant="outline" onClick={()=>setItems([...items,initialItem()])}>إضافة بند</Button><Input placeholder="ملاحظات" value={notes} onChange={e=>setNotes(e.target.value)}/><p className="font-bold">الإجمالي المتوقع: {formatSAR(total)}</p><div className="flex justify-end"><Button disabled={createMut.isPending} className="bg-navy text-white">{createMut.isPending&&<Loader2 className="size-4 animate-spin"/>} إصدار الفاتورة</Button></div></form></Dialog>
 <Dialog open={!!paying} onClose={()=>setPaying(null)} title={`سداد ${paying?.number||''}`}><form onSubmit={e=>{e.preventDefault();payMut.mutate()}} className="space-y-4"><Input type="number" min="0.01" max={(paying?.total||0)-(paying?.paid||0)} step="0.01" value={payAmount} onChange={e=>setPayAmount(Number(e.target.value))}/><Select value={payMethod} onChange={e=>setPayMethod(e.target.value as PaymentMethod)} options={Object.entries(PAYMENT_METHOD_AR).map(([value,label])=>({value,label}))}/><Select value={bankId} onChange={e=>setBankId(e.target.value)} options={[{value:'',label:'بدون حساب بنكي / نقدي'},...banks.map(b=>({value:b.id,label:`${b.name} — ${b.bankName}`}))]}/><Input placeholder="مرجع التحويل أو الشيك" value={reference} onChange={e=>setReference(e.target.value)}/><Button disabled={payMut.isPending} className="w-full bg-navy text-white">تسجيل السداد</Button></form></Dialog>
 </div>
}
